import Foundation

struct SharedAttachment: Codable, Identifiable { let id: String; let name: String; let mime: String; let filename: String }
struct SharedDraft: Codable, Identifiable { let id: String; var text: String; var attachments: [SharedAttachment]; let createdAt: Date }
enum ShareInbox {
    static let group = "group.work.eddie.com"
    static var directory: URL? {
        guard let root = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: group) else { return nil }
        var directory = root.appendingPathComponent("Inbox", isDirectory: true)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true, attributes: [.protectionKey: FileProtectionType.completeUntilFirstUserAuthentication])
        var attributes = URLResourceValues(); attributes.isExcludedFromBackup = true; try? directory.setResourceValues(attributes)
        return directory
    }
    static func all() -> [SharedDraft] {
        guard let directory else { return [] }
        let files = (try? FileManager.default.contentsOfDirectory(at: directory, includingPropertiesForKeys: nil)) ?? []
        return files.filter { $0.pathExtension == "json" }.compactMap { url in guard let data = try? Data(contentsOf: url) else { return nil }; return try? JSONDecoder().decode(SharedDraft.self, from: data) }.sorted { $0.createdAt < $1.createdAt }
    }
    static func save(_ draft: SharedDraft) throws {
        guard let directory else { throw CocoaError(.fileNoSuchFile) }
        try JSONEncoder().encode(draft).write(to: directory.appendingPathComponent(draft.id + ".json"), options: [.atomic, .completeFileProtectionUntilFirstUserAuthentication])
    }
    static func file(_ draft: SharedDraft, attachment: SharedAttachment) -> URL? {
        guard let directory else { return nil }
        // Stored file names are generated by the extension, not supplied by other apps.
        guard !attachment.filename.contains("/"), !draft.id.contains("/") else { return nil }
        return directory.appendingPathComponent(draft.id).appendingPathComponent(attachment.filename)
    }
    static func remove(_ draft: SharedDraft) {
        guard let directory, UUID(uuidString: draft.id) != nil else { return }
        try? FileManager.default.removeItem(at: directory.appendingPathComponent(draft.id + ".json"))
        try? FileManager.default.removeItem(at: directory.appendingPathComponent(draft.id))
    }
}
